### ISSUE TITLE
不能提交评论

### ISSUE THREAD

**Issue by wewall** [bimOvO/Kratos-M2#1]
版本:https://github.com/bimOvO/Kratos/commit/8285edbc28ec7dff777aa6c3985e1b780e7c21fd
无法提交评论

**Comment by wewall** [comment]
二改评论测试正常

**Comment by bimOvO** [comment]
奇怪了，本站测试正常的，要不把本站的代码批丢上来？可能是版本不一致的问题Σ(っ °Д °;)っ

**Comment by wewall** [comment]
就是弹一个什么都没有的窗口，皮的没办法

**Comment by wewall** [comment]
这就很尬，不过 加油哦https://github.com/xb2016/kratos-pjax

**Comment by bimOvO** [comment]
那个，什么都没有的窗口应该是评论被反垃圾插件误删拦截了，如果是站长发的评论，刷新下页面应该能看见；要不就在审核队列和被判定为垃圾的评论里找找。本站遇到这种情况后查询反垃圾插件的日志，都报是假阳性（意思就是误判），所以把反垃圾插件直接关掉咯╮(╯▽╰)╭

**Comment by wewall** [comment]
@bimOvO 问题所在是我没有任何插件，刷新也没有，更别提垃圾评论。只有这款主题存在这个问题。

**Comment by wewall** [comment]
@bimOvO 要不你开个新站测试下？root@119.28.181.131 passwd:qwe1230.

**Comment by bimOvO** [comment]
那个……账号什么的还是不要发上来了，毕竟公开的不怎么安全。现在估计问题是出在pjax.js的这一段代码里面，但是奇怪的是我们测试的时候都是正常的，要不换@xb2016 那个新版试试？
![image](https://user-images.githubusercontent.com/20502130/39580361-99239e8c-4f1b-11e8-87f2-4d9572a3e7f2.png)

**Comment by bimOvO** [comment]
@wewall 在在控制面板的**评论**区，看看待审队列；
以及，不知道没有设置邮件发件人会不会导致这种奇怪的错误，但是咱能想到的就是设置一下SMTP发信的相关参数试试？（外观->主题设置->邮件设置）
很皮的对话框可能是PJAX的报错和主题不兼容导致没有get任何信息╮(╯▽╰)╭

**Comment by wewall** [comment]
刚刚发布我就换了，我是看见她的start里有这个来测试试的，那个服务器你要是测试也可以的 安全无所谓的空机

**Comment by a632079** [comment]
那个， 方便提供下 OS , Browser, Logs 等信息嘛

**Comment by bimOvO** [comment]
这里有围墙提交这个bug时wordpress的记录信息：
![image](https://user-images.githubusercontent.com/20502130/39661875-d3be109c-508b-11e8-9067-7619564d0d23.png)

**Comment by a632079** [comment]
Safari ？ ， 建议贴日记。 已知 Safari JS Engine 在处理某些语法时行为和 Firefox, Chrome 完全不同。 所以有些代码会在 Safari 报错， 而在 Chrome, Firefox 正常工作。
典型例子: NodeBB, 在 v1.7.x 的时候, Safari 会提示错误， 从而无法使 pjax & socket.io 正常工作。

**Comment by bimOvO** [comment]
可是他说*二改评论测试正常*，要不就是Safari对ajax相关的函数支持不行？@wewall 能否麻烦发一下Console 的记录和日志文件？
有一个很奇怪的问题就是我的站点和 @xb2016 的站点测试评论都没有问题， 他测试时候报错，或者有没有可能是服务器的问题？（当然不排除浏览器）

**Comment by a632079** [comment]
主要还是看日记了

**Comment by wewall** [comment]
今天团建返程路上回家收拾完发，与os 浏览器无关。

**Comment by wewall** [comment]
![image](https://user-images.githubusercontent.com/33481440/39663727-1fac3460-50ab-11e8-8e84-c2f2bf604ab0.png)
![Uploading 297075CC-0FC0-4476-840B-0F09129AA358.png…]()

2018年05月05日21:32:33测试 无法重现该问题。

**Comment by wewall** [comment]
[web 控制台输出
](https://wewall.oss-cn-shanghai.aliyuncs.com/wp/uploads/2018/05/F265CCF2-389E-42D4-BC74-B35B16F0BE2F.jpg)
